"""THIRD_PARTY_LICENSES.txt 生成スクリプト。

requirements.txt (ランタイム依存) に載っているパッケージについて、
インストール済みメタデータからライセンス名と同梱のライセンス文を集める。
PyInstaller の exe にはこれらが同梱されるため、ビルド前に再生成する。

使い方:
    uv run python third_party_licenses.py
"""

import re
import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REQUIREMENTS = ROOT / "requirements.txt"
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.txt"

HEADER = """\
Third-party software notices
============================

This file lists the licenses of third-party packages that are bundled with
the distributed executable of this project. It is generated by
third_party_licenses.py from the installed package metadata.

The executable also bundles the Python runtime, which is distributed under
the Python Software Foundation License (https://docs.python.org/3/license.html),
and the PyInstaller bootloader, which is distributed under the GPL with a
special exception that allows it to be used in any executable
(https://pyinstaller.org/en/stable/license.html).
"""


def runtime_requirements() -> list[str]:
    names = []
    for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==", line)
        if m:
            names.append(m.group(1))
    return sorted(names, key=str.lower)


def license_name(dist) -> str:
    meta = dist.metadata
    if meta.get("License-Expression"):
        return meta["License-Expression"]
    classifiers = [
        c.split("::")[-1].strip()
        for c in meta.get_all("Classifier") or []
        if c.startswith("License ::")
    ]
    if classifiers:
        return ", ".join(classifiers)
    # License フィールドに全文が入っているパッケージもあるので先頭行だけ使う
    return (meta.get("License") or "UNKNOWN").strip().splitlines()[0]


def license_texts(dist) -> list[tuple[str, str]]:
    texts = []
    for f in dist.files or []:
        name = f.name.upper()
        if any(key in name for key in ("LICENSE", "LICENCE", "COPYING", "NOTICE", "AUTHORS")):
            path = Path(f.locate())
            if path.is_file():
                texts.append((str(f), path.read_text(encoding="utf-8", errors="replace")))
    return texts


def main() -> int:
    sections = [HEADER]
    missing = []
    for name in runtime_requirements():
        try:
            dist = distribution(name)
        except PackageNotFoundError:
            # colorama など他プラットフォーム専用の依存
            missing.append(name)
            continue
        meta = dist.metadata
        lines = [
            "",
            "=" * 79,
            f"{meta['Name']} {dist.version}",
            f"License: {license_name(dist)}",
        ]
        url = meta.get("Home-page") or next(
            (u.split(",", 1)[1].strip() for u in meta.get_all("Project-URL") or []),
            None,
        )
        if url:
            lines.append(f"URL: {url}")
        lines.append("=" * 79)
        texts = license_texts(dist)
        if not texts:
            lines.append("")
            lines.append("(No license file is included in the package distribution.)")
        for filename, text in texts:
            lines.append("")
            lines.append(f"--- {filename} ---")
            lines.append("")
            lines.append(text.rstrip())
        sections.append("\n".join(lines))

    OUTPUT.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.name}")
    if missing:
        print(f"not installed (skipped): {', '.join(missing)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
